"""add user's registration time

Revision ID: f865ab7c7f6c
Revises: 875323a78402
Create Date: 2018-03-14 16:48:41.629271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f865ab7c7f6c'
down_revision = '875323a78402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registerTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registerTime')
    # ### end Alembic commands ###
